using Content.Shared._Trieste.Bells.Misc;
using Content.Shared.Shuttles.Systems;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Shared.Prototypes;

namespace Content.Client._Trieste.Bells.UI;

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

[GenerateTypedNameReferences]
public sealed partial class BellConsoleWindow : BaseWindow
{
    [Dependency] private IPrototypeManager _protoMan = default!;
    [Dependency] private IGameTiming _timing = default!;

    private BellConsoleBoundUserInterfaceState? _state;
    private static readonly ProtoId<ShaderPrototype> Shader = "TP14ShaderScanLines";

    public event Action<NetEntity>? OnDestinationSelected;

    public BellConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CloseButton.OnPressed += _ => Close();

        ScanlineOverlay.ShaderOverride = _protoMan.Index(Shader).Instance();
    }

    public void UpdateState(BellConsoleBoundUserInterfaceState state)
    {
        _state = state;
        DestinationList.RemoveAllChildren();

        foreach (var dest in state.Destinations)
        {
            var button = new Button
            {
                Disabled = state.Locked || state.FtlState == FTLState.Travelling || state.FtlState == FTLState.Cooldown || state.CurrentLocationName == dest.Name,
                Text = dest.Name,
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 0, 0, 2),
                StyleClasses =
                {
                    "ConsoleText",
                    "OpenBoth",
                },
            };
            button.OnPressed += _ =>
            {
                OnDestinationSelected?.Invoke(dest.Door);
            };

            DestinationList.AddChild(button);
        }

        if (state.Locked)
        {
            StatusLabel.Text = Loc.GetString("bell-console-status-locked");
        }
        else
        {
            var location = _state.CurrentLocationName!;
            if (location == string.Empty)
                location = Loc.GetString("bell-console-location-unknown");

            StatusLabel.Text = state.FtlState switch
            {
                FTLState.Starting  => Loc.GetString("bell-console-status-liftoff"),
                FTLState.Travelling or FTLState.Arriving => Loc.GetString("bell-console-status-transit"),
                FTLState.Cooldown => Loc.GetString("bell-console-status-cooldown"),
                _ => Loc.GetString("bell-console-status-docked", ("location", location)),
            };
        }

        StatusLabel.FontColorOverride = Color.Yellow;
        TransitBar.Visible = true;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_state is not { TransitStart: { } start, TransitEnd: { } end })
            return;

        var total = (end - start).TotalSeconds;
        var elapsed = (_timing.CurTime - start).TotalSeconds;
        TransitBar.Value = total > 0 ? (float)Math.Clamp(elapsed / total, 0, 1) : 1f;
        TransitBar.Modulate = Color.YellowGreen;

        if (_state.FtlState == FTLState.Cooldown && _timing.CurTime >= end)
        {
            var location = _state.CurrentLocationName ?? Loc.GetString("bell-console-location-unknown");
            StatusLabel.Text = Loc.GetString("bell-console-status-docked", ("location", location));
            StatusLabel.FontColorOverride = Color.Yellow;
        }
    }
}
