using Content.Client.UserInterface.Controls;
using Content.Shared._Trieste.Bells.Misc;

namespace Content.Client._Trieste.Bells.UI;

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

[GenerateTypedNameReferences]
public sealed partial class BellConsoleWindow : FancyWindow
{
    [Dependency] private IGameTiming _timing = default!;

    private BellConsoleBoundUserInterfaceState? _state;

    public event Action<NetEntity>? OnDestinationSelected;

    public BellConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(BellConsoleBoundUserInterfaceState state)
    {
        _state = state;
        DestinationList.RemoveAllChildren();

        foreach (var dest in state.Destinations)
        {
            var button = new Button
            {
                Text = dest.Name,
                Disabled = state.Locked || state.InTransit,
            };
            button.OnPressed += _ =>
            {
                OnDestinationSelected?.Invoke(dest.Door);
                Log.Debug($"[Bell] Button pressed for door {dest.Door}");
            };
            DestinationList.AddChild(button);
        }

        if (state.Unsummoned)
        {
            StatusLabel.Text = Loc.GetString("bell-console-status-unsummoned");
            StatusLabel.FontColorOverride = Color.Yellow;
            TransitBar.Visible = false;
        }
        else if (state.Locked)
        {
            StatusLabel.Text = Loc.GetString("bell-console-status-locked");
            StatusLabel.FontColorOverride = Color.Red;
            TransitBar.Visible = false;
        }
        else if (state.InTransit)
        {
            StatusLabel.Text = Loc.GetString("bell-console-status-transit");
            StatusLabel.FontColorOverride = Color.Red;
            TransitBar.Visible = state.TransitEnd is not null;
        }
        else
        {
            var location = state.CurrentLocationName ?? Loc.GetString("bell-console-status-unknown");
            StatusLabel.Text = Loc.GetString("bell-console-status-docked", ("location", location));
            StatusLabel.FontColorOverride = Color.LimeGreen;
            TransitBar.Visible = false;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_state is not { InTransit: true, TransitStart: { } start, TransitEnd: { } end })
            return;

        var total = (end - start).TotalSeconds;
        var elapsed = (_timing.CurTime - start).TotalSeconds;
        TransitBar.Value = total > 0 ? (float)Math.Clamp(elapsed / total, 0, 1) : 1f;
    }
}
